### PR TITLE
New MVVM ProfileActivity set up

### LINKED ISSUE #37: ProfileActivty doesn't implement MVVM
The ProfileActivity doesn't properly implement the MVVM architecture.

### PR DESCRIPTION
**Pull request by c4ts0up**
ProfileActivity set up using MVVM. Repository still missing. UI isn't updating properly yet. Compiles? Yes. Is connected to main flow? No. Change propositions requested. close #37

### CODE REVIEW

**Comment by JuanCoronel70** [comment]
Accepted as it works in the interface ui

**Review by Daniel27110 — COMMENTED** [review]
The MVVM was followed correctly and the code works as intended. Approved.

**Review by Daniel27110 — COMMENTED** [review]
👍

**Review by JuanCoronel70 — COMMENTED** [review]
The MVVM works as expected. Good job.

**Review by JuanCoronel70 — APPROVED** [review]

**Review by Daniel27110 — APPROVED** [review]

**Pull request merged**
