### PR TITLE
Featere/campus locations fetching offline scenario

### LINKED ISSUE #53: Connectivity scenario for fetching campus locations
The user must be able to request the most updated list of campus locations using a "pull" strategy. This list of campus locations must be stored in permanent local storage.

### PR DESCRIPTION
**Pull request by Daniel27110**
Closes #53

### CODE REVIEW

**Comment by Daniel27110** [comment]
Please wait until #52 is successfully merged before approving this pull request.

**Review by JuanCoronel70 — APPROVED** [review]
Everything seems good and working.

**Review by c4ts0up — CHANGES_REQUESTED** [review]
What's the purpose of assets/edificios.json ? Is it there in compilation? Or is it pulled and saved by the user. Rebasing recommended as branch has unresolved conflicts.

**Comment by Daniel27110** [comment]
> What's the purpose of assets/edificios.json ? Is it there in compilation? Or is it pulled and saved by the user. Rebasing recommended as branch has unresolved conflicts.

As stated in the commit description, it is meant to be a fallback on the available campus locations, allowing the user to visualize the most important campus locations even if they're using the app completely offline. 

Successfully rebased.  Re requesting review.

**Review by c4ts0up — APPROVED** [review]
Build OK. Runs OK. Correct branch name and it should be good to go.

**Comment by Daniel27110** [comment]
Continued in #55, apparently renaming branches requires closing all previous pull requests.

**Pull request closed without merging**
